import { config } from 'dotenv';
config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const {
    PORT,
    SERVER_URL,
    NODE_ENV,
    DB_URI,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    JWT_REFRESH_SECRET,
    JWT_REFRESH_EXPIRES_IN,
    ARCJET_KEY,
    ARCJET_ENV,
    QSTASH_URL,
    QSTASH_TOKEN,
    EMAIL_PASSWORD,
    PAYSTACK_SECRET_KEY,
    FRONTEND_URL,
    SYSTEM_RESELLER_CODE,
    SENDGRID_API_KEY,
    EMAIL_FROM,
    REDIS_HOST,
    REDIS_PORT,
    REDIS_PASSWORD,
    BOSSU_CALLBACK_URL,
    BOSSU_API_KEY,
    BOSSU_API_BASEURL,
    BOSSU_API_ENDPOINT,
    BOSSU_API_TIMEOUT,
} = process.env;